### ISSUE TITLE
247&491&667

### ISSUE THREAD

**Issue by ziyueth** [qianguyihao/jike-yellow#2]
247
![No000247](https://user-images.githubusercontent.com/3334479/147449072-4bb5f90d-fdce-4408-8278-b3e4b19c3ae4.JPG)
491
![No000491](https://user-images.githubusercontent.com/3334479/147449129-27a0559b-f3a9-4ea7-8576-c9c0219cbca0.JPG)
667
![No000667](https://user-images.githubusercontent.com/3334479/147449282-353e2b30-05ca-4fd3-8fd3-9c5f87195a00.JPG)

**Comment by qianguyihao** [comment]
@ziyueth 已添加
